### ISSUE TITLE
wrong options in map-create.json file

### ISSUE THREAD

**Issue by ghost** [corrieb/bensdoings#5]
vic-machine/actions/1.2/map-create.json
-      "--cert-path": ".vch.auth.cert_path",
+      "--tls-cert-path": ".vch.auth.cert_path",
-      "--key": ".vch.auth.server.key_file",
-      "--cert": ".vch.auth.server.cert_file",
+      "--tls-key": ".vch.auth.server.key_file",
+      "--tls-cert": ".vch.auth.server.cert_file",
-      "--endpoint-mem": ".vch.endpoint_vm.memory_mb",
+      "--endpoint-memory": ".vch.endpoint_vm.memory_mb",

**Comment by corrieb** [comment]
Wow - good catch! I'm surprised that these changed, frankly. They would have broken everyone's scripts.

**Comment by corrieb** [comment]
I've updated the code and rebuilt the containers in DockerHub. Please let me know if there's any further issues.

**Comment by ghost** [comment]
hi, Thanks.

Sorry... two options still wrong

$ ./vic-machine-darwin create -x|grep tls
   --tls-server-key value                           Virtual Container Host
private key file (server certificate)
   --tls-server-cert value                          Virtual Container Host
x509 certificate file (server certificate)

options
--tls-key
--tls-cert

must be
--tls-server-key
--tls-server-cert

Marko




2017-10-20 15:05 GMT+03:00 Ben Corrie <notifications@github.com>:
